services:
  telifisan:
    image: irunmole/telifisan:latest
    container_name: telifisan
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - TELIFISAN_PORT=8000
      - TELIFISAN_DATA_DIR=/data
      - TELIFISAN_LOG_LEVEL=DEBUG
    restart: unless-stopped
    stop_grace_period: 30s
